title: GithHub Pages Tutorial
author: Andrew Madrid
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website created using the GitHub Pages with Jekyll tutorial
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
